set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports clkout_out]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[0]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[1]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[2]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[3]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[4]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[5]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[6]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[7]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[8]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[9]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_L]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_L]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX1_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX1_L]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX2_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX2_L]
set_property PACKAGE_PIN G14 [get_ports VCRX1_H]
set_property PACKAGE_PIN C20 [get_ports VCRX1_L]
set_property PACKAGE_PIN B19 [get_ports VCTX1_H]
set_property PACKAGE_PIN B20 [get_ports VCTX1_L]
set_property PACKAGE_PIN E17 [get_ports VCRX2_H]
set_property PACKAGE_PIN A20 [get_ports VCRX2_L]
set_property PACKAGE_PIN D18 [get_ports VCTX2_H]
set_property PACKAGE_PIN D19 [get_ports VCTX2_L]
# set_property  -dict {PACKAGE_PIN  G14  IOSTANDARD LVCMOS33} [get_ports rx1_band_sel_h]
# set_property  -dict {PACKAGE_PIN  C20  IOSTANDARD LVCMOS33} [get_ports rx1_band_sel_l]
# set_property  -dict {PACKAGE_PIN  B19  IOSTANDARD LVCMOS33} [get_ports tx1_band_sel_h]
# set_property  -dict {PACKAGE_PIN  B20  IOSTANDARD LVCMOS33} [get_ports tx1_band_sel_l]
# set_property  -dict {PACKAGE_PIN  E17  IOSTANDARD LVCMOS33} [get_ports rx2_band_sel_h]
# set_property  -dict {PACKAGE_PIN  A20  IOSTANDARD LVCMOS33} [get_ports rx2_band_sel_l]
# set_property  -dict {PACKAGE_PIN  D18  IOSTANDARD LVCMOS33} [get_ports tx2_band_sel_h]
# set_property  -dict {PACKAGE_PIN  D19  IOSTANDARD LVCMOS33} [get_ports tx2_band_sel_l]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_clock_groups -name rc_clk_mmcm_async -asynchronous -group [get_clocks rx_clk] -group [get_clocks -of_objects [get_pins i_system_wrapper/system_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]]

set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[0]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[0]/D}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[2]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[2]/D}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[7]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[7]/D}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[6]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[6]/D}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[4]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[4]/D}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[1]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[1]/D}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[3]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[3]/D}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/delay_counter_inst/cnt_reg[5]/C}] -to [get_pins {i_system_wrapper/system_i/axi_delay_counter_0/inst/axi_delay_counter_v1_0_S00_AXI_inst/count_reg_reg[5]/D}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
