set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports clkout_out]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[0]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[1]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[2]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[3]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[4]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[5]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[6]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[7]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[8]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[9]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[10]}]

# set_property  -dict {PACKAGE_PIN  G14  IOSTANDARD LVCMOS33} [get_ports rx1_band_sel_h]
# set_property  -dict {PACKAGE_PIN  C20  IOSTANDARD LVCMOS33} [get_ports rx1_band_sel_l]
# set_property  -dict {PACKAGE_PIN  B19  IOSTANDARD LVCMOS33} [get_ports tx1_band_sel_h]
# set_property  -dict {PACKAGE_PIN  B20  IOSTANDARD LVCMOS33} [get_ports tx1_band_sel_l]
# set_property  -dict {PACKAGE_PIN  E17  IOSTANDARD LVCMOS33} [get_ports rx2_band_sel_h]
# set_property  -dict {PACKAGE_PIN  A20  IOSTANDARD LVCMOS33} [get_ports rx2_band_sel_l]
# set_property  -dict {PACKAGE_PIN  D18  IOSTANDARD LVCMOS33} [get_ports tx2_band_sel_h]
# set_property  -dict {PACKAGE_PIN  D19  IOSTANDARD LVCMOS33} [get_ports tx2_band_sel_l]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]


set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[48]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[11]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[21]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[28]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[46]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[51]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[52]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[53]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[31]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[43]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[20]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[38]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[54]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[59]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[15]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[19]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[27]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[40]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[35]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[50]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[63]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[24]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[10]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[44]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[25]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[41]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[49]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[62]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[8]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[42]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[39]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[34]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[36]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[13]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[9]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[14]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[17]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[18]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[61]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[37]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[22]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[60]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[29]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[16]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[30]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[32]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[56]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[23]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[12]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[45]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[47]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[26]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[33]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[55]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[57]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[58]}]
set_property MARK_DEBUG false [get_nets i_system_wrapper/system_i/util_ad9361_adc_pack/fifo_wr_en]
set_property MARK_DEBUG true [get_nets i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_en]
set_property MARK_DEBUG true [get_nets i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_sync]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[9]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[20]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[43]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[35]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[41]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[52]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[60]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[42]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[18]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[19]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[21]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[27]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[28]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[51]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[58]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[61]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[16]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[33]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[34]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[37]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[47]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[53]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[54]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[57]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[38]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[39]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[8]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[13]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[48]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[31]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[56]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[62]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[46]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[14]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[17]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[22]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[23]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[29]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[50]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[59]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[10]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[15]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[32]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[45]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[49]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[40]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[30]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[44]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[36]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[55]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[63]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[11]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[12]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[24]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[25]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[26]}]
set_property MARK_DEBUG true [get_nets i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_ready]
set_property MARK_DEBUG true [get_nets i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_valid]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/axi_ad9361/inst/i_dev_if/i_clk/clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[0]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[1]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[2]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[3]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[4]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[5]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[6]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[7]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[8]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[9]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[10]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[11]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[12]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[13]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[14]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[15]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[16]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[17]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[18]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[19]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[20]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[21]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[22]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[23]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[24]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[25]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[26]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[27]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[28]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[29]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[30]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[31]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[32]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[33]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[34]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[35]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[36]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[37]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[38]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[39]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[40]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[41]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[42]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[43]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[44]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[45]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[46]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[47]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[48]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[49]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[50]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[51]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[52]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[53]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[54]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[55]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[56]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[57]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[58]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[59]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[60]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[61]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[62]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[0]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[1]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[2]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[3]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[4]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[5]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[6]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[7]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[8]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[9]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[10]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[11]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[12]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[13]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[14]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[15]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[16]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[17]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[18]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[19]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[20]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[21]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[22]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[23]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[24]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[25]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[26]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[27]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[28]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[29]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[30]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[31]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[32]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[33]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[34]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[35]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[36]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[37]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[38]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[39]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[40]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[41]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[42]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[43]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[44]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[45]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[46]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[47]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[48]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[49]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[50]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[51]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[52]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[53]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[54]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[55]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[56]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[57]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[58]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[59]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[60]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[61]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[62]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_sync]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk]
