# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/common/antsdr_constr.xdc

# XDC: C:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/common/antsdr_constr_lvds.xdc

# XDC: C:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/common/ccbob_constr.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_logic_inv_0/system_sys_logic_inv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_logic_inv_0 || ORIG_REF_NAME==system_sys_logic_inv_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sysid_0_0/system_axi_sysid_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_sysid_0_0 || ORIG_REF_NAME==system_axi_sysid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rom_sys_0_0/system_rom_sys_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rom_sys_0_0 || ORIG_REF_NAME==system_rom_sys_0_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_tdd_sync_0/system_util_ad9361_tdd_sync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_divclk_sel_concat_0/system_util_ad9361_divclk_sel_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_sel_concat_0 || ORIG_REF_NAME==system_util_ad9361_divclk_sel_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_divclk_sel_0/system_util_ad9361_divclk_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_sel_0 || ORIG_REF_NAME==system_util_ad9361_divclk_sel_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_adc_pack_0/system_util_ad9361_adc_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_pack_0 || ORIG_REF_NAME==system_util_ad9361_adc_pack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_dac_upack_0/system_util_ad9361_dac_upack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_dac_upack_0 || ORIG_REF_NAME==system_util_ad9361_dac_upack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp1_interconnect_0/system_axi_hp1_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp1_interconnect_0 || ORIG_REF_NAME==system_axi_hp1_interconnect_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/bd_31bd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_0/bd_31bd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_2/bd_31bd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_3/bd_31bd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_4/bd_31bd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/bd_31bd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/bd_31bd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/bd_31bd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/bd_31bd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/bd_31bd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_10/bd_31bd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/bd_c0fd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/bd_c0fd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/bd_c0fd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/bd_c0fd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/bd_c0fd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/bd_c0fd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_gpreg_0/system_axi_gpreg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpreg_0 || ORIG_REF_NAME==system_axi_gpreg_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_0_1/system_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_1 || ORIG_REF_NAME==system_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_xfer_status_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status} -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/ad_rst_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl} -quiet] -quiet

# XDC: bd/system/ip/system_util_ad9361_tdd_sync_0/util_tdd_sync_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/bd_31bd_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/bd_31bd_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/bd_31bd_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/bd_31bd_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/bd_31bd_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_srn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/xilinx/common/ad_rst_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
