set_property SRC_FILE_INFO {cfile:c:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/antsdr_lvds/antsdr_ccbob_lvds.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc rfile:../../../antsdr_ccbob_lvds.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc id:1 order:EARLY scoped_inst:i_system_wrapper/system_i/sys_ps7/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/common/antsdr_constr.xdc rfile:../../../../common/antsdr_constr.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/common/antsdr_constr_lvds.xdc rfile:../../../../common/antsdr_constr_lvds.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/common/ccbob_constr.xdc rfile:../../../../common/ccbob_constr.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/antsdr_lvds/antsdr_ccbob_lvds.srcs/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc rfile:../../../antsdr_ccbob_lvds.srcs/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc id:5 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9361_adc_dma/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/zhouzhiwen/Desktop/antsdr_standalone/hdl/projects/antsdr_e310/antsdr_lvds/antsdr_ccbob_lvds.srcs/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc rfile:../../../antsdr_ccbob_lvds.srcs/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc id:6 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9361_dac_dma/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../../../Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:7 order:LATE scoped_inst:{i_system_wrapper/system_i/axi_hp1_interconnect/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../../../Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:8 order:LATE scoped_inst:{i_system_wrapper/system_i/axi_hp2_interconnect/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../../../Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:9 order:LATE scoped_inst:{i_system_wrapper/system_i/axi_hp1_interconnect/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../../../Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:10 order:LATE scoped_inst:{i_system_wrapper/system_i/axi_hp1_interconnect/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../../../Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:11 order:LATE scoped_inst:{i_system_wrapper/system_i/axi_hp2_interconnect/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
current_instance i_system_wrapper/system_i/sys_ps7/inst
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_2 0.15
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.15
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C11" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D16" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B15" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E12" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C17" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A10" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D15" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E16" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C15" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C16" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A15" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F15" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A16" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B17" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A17" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B18" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D9" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C6" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A5" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B8" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P4" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W5" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W4" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C1" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y2" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y4" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V1" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U3" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U4" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T4" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G3" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N1" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L5" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J4" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M3" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K2" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F5" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:702 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E7" [get_ports "PS_CLK"]
current_instance
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS25} [get_ports {gpio_status[0]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS25} [get_ports {gpio_status[1]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS25} [get_ports {gpio_status[2]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS25} [get_ports {gpio_status[3]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS25} [get_ports {gpio_status[4]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS25} [get_ports {gpio_status[5]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS25} [get_ports {gpio_status[6]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS25} [get_ports {gpio_status[7]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[0]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS33} [get_ports {gpio_ctl[1]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports {gpio_ctl[2]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {gpio_ctl[3]}]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS25} [get_ports gpio_en_agc]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS25} [get_ports gpio_sync]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS25} [get_ports gpio_resetb]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS25} [get_ports enable]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS25} [get_ports txnrx]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports spi_csn]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS25} [get_ports spi_mosi]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS25} [get_ports spi_miso]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports gpio_clksel]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports clkout_in]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports iic_scl]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports iic_sda]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVDS_25} [get_ports tx_clk_out_n]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVDS_25} [get_ports tx_clk_out_p]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[0]}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[0]}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[1]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[1]}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[2]}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[2]}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[3]}]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[3]}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[4]}]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[4]}]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[5]}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[5]}]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVDS_25} [get_ports tx_frame_out_n]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVDS_25} [get_ports tx_frame_out_p]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_n]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_p]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[0]}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[0]}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[1]}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[1]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[2]}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[2]}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[3]}]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[3]}]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[4]}]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[4]}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[5]}]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[5]}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_n]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_p]
set_property src_info {type:XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports clkout_out]
set_property src_info {type:XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[0]}]
set_property src_info {type:XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[1]}]
set_property src_info {type:XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[2]}]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[3]}]
set_property src_info {type:XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[4]}]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[5]}]
set_property src_info {type:XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[6]}]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[7]}]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[8]}]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[9]}]
set_property src_info {type:XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {gpio_bd[10]}]
set_property src_info {type:XDC file:4 line:159 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:4 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:4 line:169 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/axi_ad9361/inst/i_dev_if/i_clk/clk]]
set_property src_info {type:XDC file:4 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[0]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[1]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[2]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[3]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[4]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[5]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[6]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[7]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[8]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[9]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[10]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[11]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[12]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[13]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[14]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[15]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[16]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[17]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[18]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[19]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[20]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[21]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[22]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[23]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[24]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[25]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[26]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[27]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[28]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[29]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[30]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[31]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[32]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[33]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[34]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[35]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[36]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[37]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[38]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[39]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[40]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[41]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[42]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[43]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[44]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[45]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[46]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[47]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[48]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[49]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[50]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[51]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[52]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[53]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[54]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[55]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[56]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[57]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[58]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[59]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[60]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[61]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[62]} {i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_data[63]}]]
set_property src_info {type:XDC file:4 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[0]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[1]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[2]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[3]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[4]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[5]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[6]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[7]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[8]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[9]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[10]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[11]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[12]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[13]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[14]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[15]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[16]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[17]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[18]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[19]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[20]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[21]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[22]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[23]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[24]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[25]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[26]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[27]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[28]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[29]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[30]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[31]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[32]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[33]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[34]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[35]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[36]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[37]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[38]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[39]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[40]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[41]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[42]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[43]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[44]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[45]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[46]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[47]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[48]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[49]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[50]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[51]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[52]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[53]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[54]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[55]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[56]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[57]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[58]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[59]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[60]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[61]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[62]} {i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_data[63]}]]
set_property src_info {type:XDC file:4 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_en]]
set_property src_info {type:XDC file:4 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list i_system_wrapper/system_i/util_ad9361_adc_pack/packed_fifo_wr_sync]]
set_property src_info {type:XDC file:4 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:4 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:4 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_ready]]
set_property src_info {type:XDC file:4 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:4 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:4 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list i_system_wrapper/system_i/util_ad9361_dac_upack/s_axis_valid]]
set_property src_info {type:XDC file:4 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk]
current_instance i_system_wrapper/system_i/axi_ad9361_adc_dma/inst
set_property src_info {type:SCOPED_XDC file:5 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_src_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_src_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_rewind_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_rewind_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_rewind_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_dest_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_dest_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_src_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier -filter {IS_SEQUENTIAL && NAME =~ *i_store_and_forward/burst_len_mem_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_dest_bl_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:5 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_dest_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
current_instance
current_instance i_system_wrapper/system_i/axi_ad9361_dac_dma/inst
set_property src_info {type:SCOPED_XDC file:6 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_req_response_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_response_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_dest_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_dest_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_src_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier -filter {IS_SEQUENTIAL && NAME =~ *i_store_and_forward/burst_len_mem_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_dest_bl_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:6 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_dest_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
current_instance
current_instance {i_system_wrapper/system_i/axi_hp1_interconnect/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {i_system_wrapper/system_i/axi_hp2_interconnect/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {i_system_wrapper/system_i/axi_hp1_interconnect/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {i_system_wrapper/system_i/axi_hp1_interconnect/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {i_system_wrapper/system_i/axi_hp2_interconnect/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
